### ISSUE TITLE
Expansion of features

### ISSUE THREAD

**Issue by VladislavAksiotis** [bioelectric-interfaces/nfb_studio#4] opened 2021-03-04 09:56 UTC
Below are the sections from the nfb lab xml file that are not supported by Studio. Mostly, these are the properties of the derived signal

```
 'bDisableSpectrumEvaluation',
 'sROILabel',
 'sTemporalType',
 'fTemporalFilterButterOrder',
 'sTemporalSmootherType',
 'sStatisticsType',
 'fRandomOverTime'
```

**Comment by andreasxp** [comment] 2021-03-05 03:03
I've created a table to make sure that I've got everything right.

| Property                   | Location                 | Range of Values             | Default | Extra Information                                        |
|----------------------------|--------------------------|-----------------------------|---------|----------------------------------------------------------|
| bDisableSpectrumEvaluation | ?                        | Yes/No                      | No      |                                                          |
| sROILabel                  | ?                        | ?                           | ?       |                                                          |
| sTemporalType              | Bandpass Filter          | envdetector/filter/identity | ?       | If bandpass filter is the last node, allow identity only |
| fTemporalFilterButterOrder | Bandpass Filter          | ?                           | 2       |                                                          |
| sTemporalSmootherType      | Envelope Detector        | ?                           | exp     |                                                          |
| sStatisticsType            | Derived Signal or Block? | ?                           | meanstd | I thought we scrapped this one?                          |
| fRandomOverTime            | Block                    | ?                           | 0       |                                                          |

There is quite a bit of blank spots, because we have not discussed some of these properties. As far as I understand, not all of these need to be added, because pynfb exports quite a bit of unused information.
Could you correct any mistakes and fill in the blanks for me? I will then proceed with adding the properties to NFB Studio.

**Comment by andreasxp** [comment] 2021-03-16 14:30
Implemented `sTemporalType` and `fTemporalFilterButterOrder` in master. Please take a look. I will hopefully finish the rest today/tomorrow.

**Comment by andreasxp** [comment] 2021-03-16 19:15
Implemented in master. Please verify if everything is working as intended, then you can close the issue.

**Comment by VladislavAksiotis** [comment] 2021-03-16 19:20
> Implemented in master. Please verify if everything is working as intended, then you can close the issue.

Ok, I am working on it right now

**Comment by VladislavAksiotis** [comment] 2021-03-16 20:28
Every required feature works inside Studio (I can edit it and save into xml), but there is a problem with the default values during the importing an xml created by nfb lab (there is an issue about it in the nfb repository, but I think it is the problem of studio). Should I close this issue and address the problem in another one?

**Comment by andreasxp** [comment] 2021-03-16 20:45
Yes, thank you

**Closed** 2021-03-16 22:27 UTC
Labels: enhancement
